### ISSUE TITLE
Failed to install AUR helper.

### ISSUE THREAD

**Issue by Abhiwa6** [LukeSmithxyz/voidrice#1054]
I tried to run the script on arcolinuxb fresh install. But after a dialogue {Installing "yay-bin", an AUR helper...} it fails stating some problems in line 93 i,e, no such file or directory.

**Comment by Abhiwa6** [comment]
![20211214_145337.jpg](https://user-images.githubusercontent.com/67919531/145970528-683dc25a-e590-45e4-9acc-4b71dcf26b83.jpg)

**Comment by FabianPaci** [comment]
Try to install yay manually and see if that works. Also this seems like a LARBS issue so it might be documented there.

**Comment by narukeh** [comment]
@Abhiwa6  yeah, larbs has gotten weird lately. this the voidrice repo though. but since im here...:
there is the `manualinstall` function, which downloads the PKGBUILD, and makes the package manually. if it fails, for WHATEVER REASON, the aur-helper wont be installed. In your case, you have ncurses problems, which is not essential cause its just for the TUI to look cool. And that is the first line in the function, when that fails it exits out, yay/paru wont even try/begin to be compiled/installed.
so all you have to do ins to remove the line: `dialog --infobox "Installing \"$1\", an AUR helper..." 4 50` from this function:
```bash
manualinstall() { # Installs $1 manually. Used only for AUR helper here.
	# Should be run after repodir is created and var is set.
	dialog --infobox "Installing \"$1\", an AUR helper..." 4 50
	sudo -u "$name" mkdir -p "$repodir/$1"
	sudo -u "$name" git clone --depth 1 "https://aur.archlinux.org/$1.git" "$repodir/$1" >/dev/null 2>&1 ||
		{ cd "$repodir/$1" || return 1 ; sudo -u "$name" git pull --force origin master;}
	cd "$repodir/$1"
	sudo -u "$name" -D "$repodir/$1" makepkg --noconfirm -si >/dev/null 2>&1 || return 1
```

**Comment by Abhiwa6** [comment]
Thanks. It worked for me. Hope he'll try to fiz this issue ASAP
