### ISSUE TITLE
some advice

### ISSUE THREAD

**Issue by blinky39** [LukeSmithxyz/voidrice#1206]
- the samedir(sd) script can be rewritten in a more simple way, just one line:
```
cd `pwd` && setsid $TERMINAL &
```
- in .xprofile, I found that by just adding pipewire and pipewire-pluse in autostart will no wake sound card(MOD+F4, F3 Cards shows no data) upon startx, so I searched  [artix wiki ](https://wiki.artixlinux.org/Site/PipewireInsteadPulseaudio) and found they recommand appeding ` /usr/bin/wireplumber &` in .xprofile. That did works, I don't know it's a common issue or not, maybe you want to add it?
(btw you don't need pipewire-pulse in autostart list)

**Comment by LukeSmithxyz** [comment]
Samedir cannot be rewritten by such because it's designed to be run in certain tui programs as well that don't communicate the pwd properly. As it happens, it doesn't work either way in lf, which is used as the file manager now, so it's questionably useful now. That's why it's not a keybind anymore.
