### ISSUE TITLE
Does anyone have any iwd dmenu script for wifi?

### ISSUE THREAD

**Issue by pineapples5972** [LukeSmithxyz/voidrice#1229]
I am looking for pure iwd dmenu script for wifi selection. I wonder why this repo still lack such basic functionality even today. We should able to do wifi selection from dmenu.

**Comment by aymey** [comment]
Why would you need it? I feel like the only use would be for cafe wifi or somehing like that, and even then you probably wont be using the script often. You can just do `iwctl station list`, `iwctl station wlan0 connect "..." ` so is the script really neccessary for such a short command? Like most scripts are used because its not easy just to tyoe in a command like iwd can be. On top of this if you did want to write a script it would be like 10 lines so i dont think its that neccassary, ive never once thought a script would be more convenient but maybe thats just me idk. I guess you could make a pr but i just wanna know its use cases?

**Comment by pineapples5972** [comment]
Dmenu is always convenient above writting commands everytime you need to do scan or connect to new wifi.
you can put the script at prefered keybind and have it available for you at your fingertips. 
for the primal tasks like bluetooth and wifi we have to rely networkmanager applet in the systray. which is both unneccessary gtk bloat plus heavily rely on mouse. I am not a programmer or script writer but I tried my best to write one but iwctl output is too fancy to scrape the proper thing with regex using grep, sed or awk at least for noob like me. So thats why i made issue jokingly but still hoping for some positive response from the community who delievered best scripts using dmenu i've ever seen. 

If I ever succeded in writing script for iwd i will make a pr but until then I'll have my hopes on that someone there must have already made it or atleast got idea how to do it.(the difficult regex part).
