### ISSUE TITLE
tap  to click is not working. 

### ISSUE THREAD

**Issue by jashimgit** [LukeSmithxyz/voidrice#128]
Hi, Luke thanks for your awesome scripts. 
I am using your scripts for my Arch labs and i  am so much eager for web developing with my Arch lab indeed. I want to be permanent with i3. I have found that when i try to tap to click in my touch pad its not working. 

I am using Dell 3421 model with Arch linux.
so i think you check this out. 

thanks.

**Comment by LukeSmithxyz** [comment]
Apologies for now answering this before, but to my understanding, this isn't something that can be fixed with changes to the home dotfiles. Check the [Arch Wiki article on `libinput`](https://wiki.archlinux.org/index.php/Libinput) to see how to globally enable tap to click on the system.

I might conceivable enable this feature, but if I do so, I don't think it can be done in these dotfiles, and must be manually setup in by the LARBS script. Some one can feel free to tell me if there is a hack for this another way.
