### ISSUE TITLE
wget hsts-file

### ISSUE THREAD

**Issue by levdopa** [LukeSmithxyz/voidrice#1286]
your wgetrc file has one line in it
`hsts-file=~/.cache/wget-hsts`
hsts-file isn't a command that can be found on https://www.gnu.org/software/wget/manual/wget.html#Wgetrc-Commands
and it gives an error when I source wgetrc

Do you also get an error when you source it?

**Comment by iStagnant** [comment]
Yeah `hsts-file` is a flag of wget used like this `wget --hsts-file=THE FILE IT SHOULD BE SAVED TO`.
Search the page and you'll find it, by default wget saves the file to your home directory so in the wgetrc luke changes it to store it in `.cache/` to clean the home directory.
And another thing when you source a file i.e `source .config/wgetrc` the file is executed by the shell so when you do that, what you're technically doing is running this command in your shell `hsts-file=~/.cache/wget-hsts` which is obviously going to give you an error, since `hsts-file` isn't a command but flag/option of the wget command.
