### ISSUE TITLE
shortcuts key [noob Q]

### ISSUE THREAD

**Issue by tjallemaal** [LukeSmithxyz/voidrice#1328]
![pic-selected-230521-1632-04](https://github.com/LukeSmithxyz/voidrice/assets/69585777/48e31129-3083-4eda-be89-4c6ba7f393bf)

the shortcuts on the left side, what prefix do they have? I'm hitting random keys but yeah [...] thxx

**Comment by emrakyz** [comment]
What do you mean exactly?

These are "shell" aliases and for Luke's config files the shell is "zsh". Alias means a "short name". 

Basically, you need to use those inside a terminal.

For example, if you write "cfz" and enter, this file will be opened: "/home/username/.config/zsh/.zshrc"

**Comment by tjallemaal** [comment]
alright!
yeah that's what i was wondering. like where to enter it.  sorry i feel kinda dumb about it. 
thx emrakyz

**Comment by tjallemaal** [comment]
but then again, it feels more intuitive to give them keybinds on a higher level. like in the dwm config, so i dont open the terminal in the first place. that was my first thought. hm anyways. larbs is saving my life

**Comment by emrakyz** [comment]
@tjallemaal You can do that. You can add a line to open a file with a keybind if you need that kind of an access for a file. Since you already need a terminal to open a config file in a text editor, it wouldn't make sense in my opinion but it's easy to do that and you are free to do so.

Learning the complete system can take time. It's not dumb, don't worry. It gets easier with time. Have fun!
