### ISSUE TITLE
Failed to connect to pulseaudio when booting with headphone already connected

### ISSUE THREAD

**Issue by BEST8OY** [LukeSmithxyz/voidrice#1393]
Hello
So, the thing is when I boot into the system while the headphone is already connected to laptop Puslemixer doesn't work. 
In this situation the headphone works but when I plug the headphone out the speakers don't work.

If I boot into the system without connected headphone, Pulsemixer, speakers and headphone all work fine!

What should I to avoid this problem??

**Comment by BEST8OY** [comment]
Not sure what happened!
For now it's okay.
If it happened again I'll reopen the issue!

**Comment by BEST8OY** [comment]
Okay.
The problem is with pipewire config file in /.config I removed that and now everything is good!
It sometimes causes the statusbar scripts to not load or sometimes when they load the pulsemixer only shows dummy audio.

**Comment by appeasementPolitik** [comment]
Had the same issue. Boot with headphone connected and everything is fine, but boot without headphone or unplug and replug the headphone, and it doesn't work anymore.

Fixed it by removing `~/.config/pipewire/pipewire.conf`, and replacing it with `~/.config/pipewire/pipewire.conf.d/user-session.conf` with the following content:

```
context.exec = [
    { path = "/usr/bin/wireplumber" args = "" condition = [ { exec.session-manager = null } { exec.session-manager = true } ] }
    { path = "/usr/bin/pipewire" args = "-c pipewire-pulse.conf" condition = [ { exec.pipewire-pulse = null } { exec.pipewire-pulse = true } ] }
]
```

Also has the advantage of being more future-proof. I didn't need to install `alsa-firmware` or `alsa-utils` like in the linked issue. The second reason for the problem was that I had set the output to `Analog Stereo Output`. Setting it to `Analog Stereo Duplex` fixed it.

**Comment by bybv** [comment]
Thank you so much for this. I will do a fresh install and see if this solves my issue. I had the same issue where Super+F4 pulled up a blank pulsemixer and couldn't figure out the pattern. 

However I'm not following your note about the analog stereo output vs analog stereo duplex. Where were you making these selections?

> Also has the advantage of being more future-proof. I didn't need to install `alsa-firmware` or `alsa-utils` like in the linked issue. The second reason for the problem was that I had set the output to `Analog Stereo Output`. Setting it to `Analog Stereo Duplex` fixed it.

Cheers!
