### ISSUE TITLE
[HELP] Transparency

### ISSUE THREAD

**Issue by duncan-f** [LukeSmithxyz/voidrice#14]
Could you please explain to me how did you manage to get true transparency on your URxvt windows without using these 2 lines on your config :
```
URxvt.transparency: true
URxvt.shading: 35
```
Thx.

**Comment by samosaara** [comment]
Oh yes it was also not clear to me how to setup transparency, 

I _uncommented_ these lines on .Xdefaults 
https://github.com/LukeSmithxyz/voidrice/blob/0e171e78ba9afa3dba53a0e9df3324f404d6b762/.Xdefaults#L33

I'm not sure if actually related, because I know uxrvt can do some background image trickery to create fake transparency, but I also enabled compton (composite manager), on i3's config.

**Comment by duncan-f** [comment]
Thx for the answer, but i tried with the line you mentioned. No chance!
I tried with this too:
URxvt.background:    rbga(0, 0, 0, .7)
There's no way to make it work. I copied the compton.conf file from Luke's repo, couldn't make it work either.
@samosaara could you share with me your compton.conf file.

**Comment by samosaara** [comment]
I did not edit @LukeSmithxyz's compton config it is the same one of the repo. You do realize that compton is a dependency and a software itself that must be run and etc? Try killing it and running in non-daemon mode to ensure it's starting and working properly.

**Comment by LukeSmithxyz** [comment]
@duncan-f So the context I should give is that there's a bunch of commented junk in my config that I need to clean up. These lines:
```
URxvt.transparency: true
URxvt.shading: 35
URxvt.background: rbga(0, 0, 0, .7)
```
Are useless with i3 and urxvt due to compatibility problems. I've just used this on a non-i3 WM and didn't delete them. As @samosaara said, the proper way (and only one) to enable urxvt transparency on i3 is with compton (the config in this repo does it) and by uncommenting the line he mentioned (and yes, the number in the brackets is the alpha value).

Your question is a good one though, and I get it a lot. I'm thinking of creating a dialog settings menu in LARBS/this repo that will allow you to change settings such as transparency/use of pywal/etc. without have to figure it out. Either way, I'll probably add documentation to this effect in the next push.

**Comment by duncan-f** [comment]
I got it right thank you very much guys for your answers.
It was my bad, compton wasn't starting and i didn't realize it.

And for those who'll end up on this issue, i just used this:

URxvt.background: [75]#000000
