### ISSUE TITLE
Mod+7 and Mod+Shift+7 has unexpected behavior

### ISSUE THREAD

**Issue by LJNielsenDk** [LukeSmithxyz/voidrice#211]
Mod+7 opens a terminal and Mod+Shift+7 closes the active window instead switching to or moving the current window to 7th virtual desktop respectively as I'd expect it to given how all the other numbers behave with the Mod key.

Is this intentional? If so then I'd like to know why and suggest adding a note about it somewhere in the Mod+F1 document too.

**Comment by LJNielsenDk** [comment]
@richard134 Huh, turns out it works for me with the US layout too.

I set my layout with `setxkbmap -layout dk,us` but if I switch it around so it's `us,dk` it works as expected.

I'm not sure I understand the part about groups at the bottom of section 4.3 in your link.
Assuming `setxkbmap -layout dk,us` when I press the key the keycode is translated to the keysym that it corresponds to in the dk layout?
If so, how come it doesn't match with the keysym-based binding?
If not, how does it work and what do they mean by it being translated in Group1 by default?

**Comment by stormsz** [comment]
i just would like to point out that, this solution doesnt work for everyone. 
setxkbmap us,pt doesnt work. i tried a bunch of other stuff to get it to working but in the end i just manually did the keybinds switch from US to PT

**Comment by dr3mro** [comment]
I use Finnish Keyboard and I had same issue was able to fix it by commenting those 2 lines from i3 config file 
#bindsym $mod+apostrophe	split horizontal ;; exec $term
#bindsym $mod+slash		split vertical ;; exec $term

**Comment by stormsz** [comment]
Ok guys, i think i found an "universal" solution, but that would need Luke to change how he binds the keys on is i3/conf file.

so as we know theres the problem with the <meta>+apostrophe bind (and others) since, in my case the apostrophe is located on the 7 button, so when i press <meta>+7, it opens an terminal instead of the workspace switch.

the solution that i found:
`bindsym` binds to the simbols, so` bindsym $mod+a` binds to the letter a 
**BUT!**
`bindcode `binds to the **physical KEY** also the bindcode doesnt user simbols instead is uses keycodes, this can easly be found with something like `xev`, so the slash bind, i know that the key is the `-` on my portuguese keyboard, so `xev` guives me `keycode: 61`


so the bind would be something like
bindcode $mod+61 split horizontal ;; exec $term

**Comment by LukeSmithxyz** [comment]
Yeah, I'm aware of this fix @stormsz . I've been reticent to make that shift because:

- It makes the i3 config pretty intuitive and hard for users to modify and the README might also need to vary based on keyboard layout.
- On keyboards where there are keys shifted over, I believe a lot of the mnemonics are lost or the visual logic of where the keys are.

Now, if the problem is *only* with the number keys, I suppose I could just switch them over to using `bindcode` just for them, but I'd want to know what other keys produce problems.

Realistically if there are other lurking interferences, I can make these changes, but I'd want people with non-us keyboards to test it out and see what kinds of problems there might arise first.

**Comment by Sercurio** [comment]
I installed larbs on void yesterday.

I have a fr azerty keyboard, some of the shortcuts seems ok but first of all Mod + Enter doesn't open a terminal.

Moreover Mod + 3, is also Mod + " on fr layout.
