### ISSUE TITLE
Pacpackages recommends running pacman -Sy

### ISSUE THREAD

**Issue by webarnes** [LukeSmithxyz/voidrice#225]
Running `pacman -Sy` is [potentially dangerous](https://wiki.archlinux.org/index.php/System_maintenance#Avoid_certain_pacman_commands) if you later install new software using pacman -S (because the earlier Sy updated the package database, you'll get the newest version of the package but might not have the correct version of its dependencies).

`checkupdates | wc -l` is safer plus can be run as a normal user. I'm not 100% sure whether `checkupdates` is installed by default on Arch (it is part of pacman core on Manjaro, but I've seen some posts suggesting it was moved to the pacman-contrib package on Arch).

**Comment by LukeSmithxyz** [comment]
The only situation under which this could cause breakage is if:

- a cron runs `-Sy`
- `pacpackages` give a notification that there are packages to update
- the user ignores it and manually installs another package with `-S`
- some library incompatibilities occur
- the user doesn't know how to either `-Su` or click the update icon to fix the problem

I know that there is a recurring meme among Arch users that this is "dangerous", but considering these dotfiles are literally nagging you with an icon which when clicked would solve any potential problems, I'm not worried.

If it means anything, I've had `-Sy` run in the background for months now without any problem. Any problems that do occur will be fixed by updating mannually or clicking the icon. My assumption is that any person who knows how to set a cronjob, can also figure out how to update.
