### ISSUE TITLE
How do you get the scratchpad?

### ISSUE THREAD

**Issue by DrDonkey** [LukeSmithxyz/voidrice#24]
I don't get the scratchpad thing. For $mod+a you have mentioned scratchpad, and I don't have anything named that. Tried searching in aur but no luck.

**Comment by voidanix** [comment]
@DrDonkey Well, $mod+a should open an instance of `R`, and uses the scratchpad for *closing* that instance (it actually hides it, for reusability).
If you need to get to the scratchpad you must bind a command to get there through the i3 config (e.g. add `bindsym $mod+minus scratchpad show` to make `$mod` and `-` take you to the scratchpad).
The i3 config is located `~/.config/i3/config`.

**Comment by LukeSmithxyz** [comment]
If you're trying to say that nothing happens when you press mod+a while using my configuration, this is likely because it is not spawn because you don't have R installed, which as voidanix said, is what the scratchpad uses.

Either install R or go into the config and change the line that spawns the R calculator to Python or some other interactive shell that can be used for math.

**Comment by DrDonkey** [comment]
R means R "the programming language"

**Comment by voidanix** [comment]
Yea, `R` is an interpreted language and is mostly used for creating statistics. It's a very useful tool.

If you used `LARBS`, then `R` should be already installed.
