### ISSUE TITLE
LARBS weird issue

### ISSUE THREAD

**Issue by DrDonkey** [LukeSmithxyz/voidrice#247]
![pic-full-190316-0924-49](https://user-images.githubusercontent.com/18498932/54470294-7ba83600-47cd-11e9-92bb-d097543ada38.png)
I installed LARBS yesterday. _It was quite a journey installing arch._

And I am seeing the above behavior shown above. In above case I already have a session. When I press mod+u, the drop down terminal shows up but both original and drop down terminal are of same size. I can resize the drop down terminal to resize the terminal in the background but it is irritating. 
I checked `tmuxdd.`
And removed `tmux a` part for now.
Can we do something about the resizing part?

**Comment by LukeSmithxyz** [comment]
This is a natural part of tmux. If you don't want  it, remove the `a` so that the dropdown session does not try to connect to your other tmux session, thus resizing it.

There may be a way of preventing the resizing of attached sessions, but I don't know about it off the top of my head. Check the tmux manual if you need it.
