### ISSUE TITLE
Increasing st font size fails

### ISSUE THREAD

**Issue by Anecyal** [LukeSmithxyz/voidrice#297]
st doesn't seem to want to increase font size, and launching screenkey shows me that alt+shift is bound to "Alt+ISO_Next_Group" I'm not sure where in xdotool it is triggering that. Fresh Arch install.

**Comment by LukeSmithxyz** [comment]
Do you have some weird keyboard mapping going on? What's your lang and locale?

**Comment by Anecyal** [comment]
C, en_US.utf8, POSIX. I've only switched between colemak and standard US layout with setxkbmap

**Comment by sarpik** [comment]
Alt+Shift is usually for locale changing, just like in windows. For example, I use Lithuanian and English locales & switch between them.

I've rebound re-sizing to alt+n and alt+m since they were available.

You can do the same if you compile the `st` repo yourself, since you can modify the source code (which is intended). And it's pretty simple.

`st/config.h`:

```c
static Shortcut shortcuts[] = {
    /** {...}, */
	{ MODKEY,               XK_m,           zoom,           {.f = +1} }, /** `MODKEY + `m` instead of `TERMMOD` + `K` because SHIFT+ALT changes language */
	{ MODKEY,               XK_n,           zoom,           {.f = -1} }, /** `MODKEY` + `n` instead of `TERMMOD` + `J` because SHIFT+ALT changes language */
	/** {...}, */
};
```
