### ISSUE TITLE
i3-blocks doesn't seem to update

### ISSUE THREAD

**Issue by TomJansen** [LukeSmithxyz/voidrice#307]
Hi. After installing your dotfiles 2 days ago i3blocks doesn't update the statusbar anymore. Maybe this has to do with the change of the scripts location?

**Comment by LukeSmithxyz** [comment]
What isn't updating? The time? the weather? the volume? the music? or just everything?

I think I can see what would cause breakage in the music/mpd module: it relies on the `mpdupdate` script running as a daemon to detect when to update. I've added it to the `.xinitrc` (it was originally in the i3 config).

Is this the problem or is there more?

**Comment by TomJansen** [comment]
Ah yes I believe that this was the error.
About the volume module, when I previously installed the dotfiles, the volume module would update after closing pulsemixer (when also setting the volume with pulsemixer) this is not the case anymore.

**Comment by LukeSmithxyz** [comment]
Okay. I know what changed. That should be fixed too: just an extra `pkill` commanded needed in the binding.

Does the volume module still change when you change the volume with `mod-+/-`, etc.?

**Comment by TomJansen** [comment]
>Does the volume module still change when you change the volume with mod-+/-, etc.?
yes, but left clicking the vol module and then changing the value via pulsemixer does not update the vol module. I know it is a very tiny issue, but it is a regression.

**Comment by LukeSmithxyz** [comment]
Oh so you're talking about when you click to get pulsemixer, rather than when you press `super + shift + a` for it?

I understand. So this is actually a problem with how you can spawn dependent processes and such. Basically I had two choices:

- Have the volume module autoupdate after (the clicked on version of) pulsemixer closes, OR
- Allow users to click to get pulsemixer, but still have the i3 bar capable of taking new changes while the pulsemixer instance is opened.

I chose the second as I don't think having both is possible easily. Now if the second one isn't working for you anyway, tell me and I'll change it to allow the first, but that's the problem at hand.

**Comment by TomJansen** [comment]
>Allow users to click to get pulsemixer, but still have the i3 bar capable of taking new changes while the pulsemixer instance is opened.

With the latest fix, this works now with ``$mod + shift +a`, but not when clicking the module

**Comment by LukeSmithxyz** [comment]
Yes, that's what I meant. It's only the instance spawned by the i3block instance that is the problem.

Realistically speaking I don't really see a band-aid for this little blip. There are similar problems with the other clickable programs as well. I'm going to close this issue because I think it's about as fixed as it can be. Any other interaction with the modules should fix them afterwards.

**Comment by TomJansen** [comment]
My pull request adds choice 1 when clicking the vol blocklet, leaving choice 2 intact for `$mod + shift +a`

**Comment by TomJansen** [comment]
Oops, scratch that. Sorry
