### ISSUE TITLE
After login the keyboard layout changes to us instead of the locale set when installing Arch.

### ISSUE THREAD

**Issue by EmiliaTrollrosse** [LukeSmithxyz/voidrice#314]
I'm trying to get my local keyboard layout after login. In my case Swedish (se)

If I switch to tty 2 at the login promt and log in, the keyboard uses the swedish setting at the prompt.

After logging in the keyboard layout changes to us. I think this hs something to do with the .xprofile file.

I've tried to comment out the setxkbmap line, but nothing changes after reboot.

I tried to add the -layout flag but that did'nt work.

```
# Switch to Swedish international with Caps as Mod/Escape
setxkbmap -layout se -option caps:super -variant altgr-intl && killall xcape 2>/dev/null ; xcape -e 'Super_L=Escape' &
```

If I give the setxkbmap command in the terminal, I get swedish keyboard layout.

```
setxkbmap se
```

How can I get swedish keyboard layout and keep the Caps as Mod/Escape?

**Comment by badmrfrosty** [comment]
Hi, I got the same problem. The variant option is the problem because there is probably no altgr-intl for Swedish. You should replace the setxkbmap line in .xprofile with this one : 
# Switch to Swedish with Caps as Mod/Escape
setxkbmap -option caps:super -layout se && killall xcape 2>/dev/null ; xcape -e 'Super_L=Escape' &

**Comment by EmiliaTrollrosse** [comment]
Hallo Badmrfrosty!

That work great, thank you very much! :)
