### ISSUE TITLE
Suggestions for Source Code location

### ISSUE THREAD

**Issue by LukeSmithxyz** [LukeSmithxyz/voidrice#319]
The voiddwm version will be cloning and compiling several suckless programs and I think I'd like it to maintain the source code for the user's later editing. The question is where should this source code be?

Right now, I have it go to `~/repos/` which is where I have it on my machine for historical reasons, but ideally, I'd like:

- somewhere hidden
- somewhere that minimizes mess in the home directory

I can easily set and inform users of a shortcut to wherever. As far as I know, there's no XDG standard for user-specific source code, otherwise I'd just put it there and call it a day. A place in `~/.config/` or `~/.local/` might make sense.

If anyone has any suggestions feel free to vocalize them.

**Comment by ndalliard** [comment]
What about `~/.src/`? I have it personally in `~/src/`, comparable to your `~/repos/`.

**Comment by lhindir** [comment]
I think `src` is best left to source files within specific project/repository folders (alongside `bin`, usually). Many programs that could live in this folder probably would have `src` folders within each one, so I like `repos` because it doesn’t create any confusion over what `src` usually implies as a name. It would be weird to `ls` and think your entire home directory is a repository of some kind. Something like `~/.local/repos` would get my vote.

This is the irritating part about suckless software, for me. The idea of directly modifying the source code is nice, but having a dedicated config file is much more modular. It might make sense to put these programs in `.config`, but the idea of keeping entire source code repos there doesn’t seem right at all, small though they may be.

**Comment by hamlinux** [comment]
vcsh as described in git minutes episode 13 seeks to control the home directory as a single repo also.  It is not under active development right now but is currently in arch repo.

**Comment by kpatel28** [comment]
You could mirror the structure of /usr/local/ and put source code in .local/src/, then make symlinks to the compiled program in .local/bin/ or change the Makefile to compile into .local/bin/ automatically. Keeps things hidden, separated, no new PATH additions, and sorta follows convention.
