### ISSUE TITLE
Unable to change default browser

### ISSUE THREAD

**Issue by Halikular** [LukeSmithxyz/voidrice#385]
I've been trying to change the default browser via changing the `export BROWSER="firefox"` variable to `"w3m"` that doesn't work. I've also tried using xdg-utils to no avail. 

Update:
When running $BROWSER it will start the correct browser, however launching the browser from other software such as lutris, gimp and such will yield only firefox-nightly.

**Comment by LukeSmithxyz** [comment]
w3m can't be run as an independent browser as it is terminal-based. You could try setting your `$BROWSER` to `$TERMINAL -e w3m`, but that still wouldn't work as you might expect.

As for firefox-nightly being opened from other applications, that's because those will be using `xdg-open` to search for a browser and don't care what you set `$BROWSER` too. You'll have to look up changing your `xdg-open` defaults for that.

**Comment by kronikpillow** [comment]
had the same problem when I changed the $BROWSER to brave or chromium or chrome, or basically any other browser ... tried the xdg-open change of default browser, but it doesn't allow it as the default browser is set via $BROWSER ... so the only way i found a workaround for this is by removing firefox from the system

**Comment by Halikular** [comment]
I have tried changing it with e.g. `xdg-settings set default-web-browser google-chrome-stable.desktop` the command fail with this: `xdg-settings: $BROWSER is set and can't be changed with xdg-settings`. `xdg-settings get default-web-browser`gives: google-chrome.desktop. So I don't really understand what's not working here.

**Comment by kronikpillow** [comment]
I already told you, the way to change the default web browser is to change the $BROWSER variable in your .profile or .zprofile .... or to remove it completly, and set it with xdg-settings set default-web-browser, but the 2nd option is not good as a lot of lukes config use the $BROWSER variable

**Comment by Halikular** [comment]
In that case I assume it's some developers that ignore the xdg-settings.
