### ISSUE TITLE
Update issue

### ISSUE THREAD

**Issue by focus85** [LukeSmithxyz/voidrice#405]
So i have been using larb’s for a while (almost a year without any update) and today for some reason decided to update the current version of larb and used the same username which ruined everything however everything seems ok when I create a new user with the larb wizards. Any suggestions/comments are appreciated 🙏

**Comment by LukeSmithxyz** [comment]
You'll have to tell me what "ruined everything" means for me to know what went wrong.

**Comment by dinesh0430** [comment]
I have used LARBS(i3) on Manjaro for nearly 3 months and everything went smooth till yesterday. I decided to reformat the HDD and installed Manjaro once again. Then installed the LARBS script after updating the system. I gave a new username and after the script said there are no hidden errors I rebooted the PC and when I gave credentials to new user then the i3blocks and wallpaper loaded fine but the keymaps have not been loaded and the I can't access the terminal. So I re-installed manjaro and tried dwm-larbs (new user) after updating the system and the same problem came again. So I re-installed manjaro and tried i3-larbs with existing user and when rebooted, first few seconds wallpaper changed to larbs wallpaper and then the xfce4wm kicked in again. Please tend to this issue and if you want any extra details regarding the issue please ping me.

**Comment by LukeSmithxyz** [comment]
What is in your `/etc/locale.conf`? That XOpenIM error I believe is locale related.

**Comment by dinesh0430** [comment]
What about the LARBS issue?

**Comment by LukeSmithxyz** [comment]
Yes I've been making substantial changes in the past 48 hours, so I need to be sure when exactly you installed it. If you ran it several hours ago, your problem may have already been fixed.

But as I said, the terminal not coming up is likely a locale issue.

**Comment by dinesh0430** [comment]
Ok, I run the LARBS again and tell about the proceedings.

**Comment by dinesh0430** [comment]
So, I have re-installed manjaro and the results are pretty bad for me!
I chose the i3-larbs for existing user and got the below screen. 
![Screenshot_20191124-232129](https://user-images.githubusercontent.com/32917000/69498845-46361980-0f12-11ea-9419-9f5e72e074f5.png)
The xfce4wm got kicked in.

**Comment by dinesh0430** [comment]
After this I tried dwm-larbs on a new user and the below image is the result:
![IMG_20191124_231726](https://user-images.githubusercontent.com/32917000/69498892-c6f51580-0f12-11ea-8c50-4b0cd4ffa457.jpg)
I thought that everything is working fine with the dwm-larbs, but I am only able to load the *welcome pdf* and even dmenu is not taking any input (dmenu appears after pressing super+d but if we press any key it will exit immediately). 
The zathura pdf inverse mode seems to be working fine which could mean that the applications have been installed and the config files placed correctly but the key binding like super + (i,enter,m,r) have not been loaded but the menu key has been successfully remaped to super key and the super+q works to kill an application(i3 default is super+shift+q)
It seems like i3 has been loaded instead of dwm but the documentation explicitly specifies dwm.

**Comment by dinesh0430** [comment]
What about the issue? Is the LARBS still under development state?
I will try out the larbs in regular intervals and see the results. I am grateful that you are doing this all for free of cost. So, I won't pressurize you regarding the issue. Take your time and debug.
Cheers!

**Comment by LukeSmithxyz** [comment]
Well I can tell you the issue: I haven't yet worked out LARBS to work with display managers (login screens). Since I don't use OSes with preinstalled graphical environments, I usually cater LARBS for use with a classical terminal/tty login. So people who run LARBS from a graphical Manjaro install or whatever have run into unexpected issues that I'll have to fix as they arise.

I'll have to play around with the `~/.xprofile` and other files with different DM. I might have some time today. I'll see.

I'll tell you that the way I have it right now is that whenver you start a graphical environment, `~/.xinitrc` will decide whether to boot LARBS with dwm or i3. It works well for me, but DMs do things a little differently, and it looks like yours runs conflicting commands that put you in the wrong WM. Since you choose your WM manually in a DM, this conflicts in some way. I'll have to do some revising because I'm not super familiar with how DMs tend to work in the backend since I don't really use them.

**Comment by 20jam** [comment]
I'm getting a bug after fresh install of LARBS, all the keyboard shortcuts works fine, but the ones related to launching apps such as ranger, st, web browser DON'T work at all #HELP :((( (Three times tested with fresh linux install, end up same issue)

**Comment by LukeSmithxyz** [comment]
Which keyboard shortcuts do work then?

Show me the output of `echo $TERMINAL`.

**Comment by 20jam** [comment]
nothing =/empty output

**Comment by LukeSmithxyz** [comment]
Okay. As a little fix, add:

```
source ~/.zprofile
export FILE="ranger"
export STATUSBAR="i3blocks"
```

To the **top** of your `~/.xprofile` and reboot. See if that fixes it. I'll have to make general arrangements for DMs.

**Comment by 20jam** [comment]
Okay its seem to be better now, mod + enter & m & n & A works but all other basic progrems doesn't including the browser. Thanks alot

**Comment by LukeSmithxyz** [comment]
Are you sure you added it to the top of the file? I needs to be above the `sxhkd` line especially.

**Comment by 20jam** [comment]
Yes, after #!/usr/bin/env sh

**Comment by 20jam** [comment]
Okay  I had to run the browser from demenu for the shortcut to work. I think this fixed my issue. Luke I'm really greatful for your work.

**Comment by LukeSmithxyz** [comment]
I've resolved these issues in the most recent commits. You should get all the right environmental variables whether you're logging in via tty or DM now. Force pull the newest commits to fix the problems.
