### ISSUE TITLE
DWM Status bar?

### ISSUE THREAD

**Issue by AlexSyssoyev** [LukeSmithxyz/voidrice#411]
Hello, how do you configure the dwm status bar? the dwmstatus file in .local/bin/ does not exist anymore, and i cant find any file that works for it.

**Comment by DariusOS** [comment]
I second this. I keep going back to the YT videos and notice I may have more files missing as well. Nonetheless, after tinkering around the configs for a while, everything seems to be running alright on my XPS 7590, but the build overall still misses key components, especially when compared with what LARBS showcases on the channel. In my case, there's no config.h and dwmbar. Anything else I'm sure can be done manually if found missing.

**Comment by LukeSmithxyz** [comment]
I use https://github.com/LukeSmithxyz/dwmblocks now, which is significantly better because there is a modular update routine that allows you to send update orders for particular blocks so you don't have to be running a script constantly that rechecks everything.

If you want the stuff in most of my older videos, that's probably i3 (and i3blocks as a statusbar) which will now come will each fresh install of LARBS in additional.

If you want to look at the old dwm bar script, revert 6244ad78ac5be212dc996cb4919cd778c3e7e7dd and you'll have it back.

**Comment by LukeSmithxyz** [comment]
Actually, excuse me, it looks like it was deleted in a5e66ac4f45322b3665c944ba34d83b7db43ebc5.
