### ISSUE TITLE
Error on install in Void

### ISSUE THREAD

**Issue by drake-newell** [LukeSmithxyz/voidrice#412]
An attempt to run larbs.sh on Void produces an error:
`error automatically updating Arch keyrings`
As I am not running arch, what does this mean?

**Comment by Sercurio** [comment]
Hello,
I had facing this issue yesterday too.

I think it's this function : 
```
refreshkeys() { \
	dialog --infobox "Refreshing Arch Keyring..." 4 40
	pacman --noconfirm -Sy archlinux-keyring >/dev/null 2>&1
	}
``` 
can you try to comment it before running the script ?

Or we can test if the pacman package is installed before running it with : 
```
if type pacman >/dev/null 2>&1; then
refreshkeys() { \
	dialog --infobox "Refreshing Arch Keyring..." 4 40
	pacman --noconfirm -Sy archlinux-keyring >/dev/null 2>&1
	}
fi
```
I suppose.
Regards

**Comment by LukeSmithxyz** [comment]
Yeah that's it. I've only been testing it on Arch distros so I haven't bothered removing all the Arch-isms. I think I'm going to temporarily remove that line anyway since refreshing keyrings, despite being sometimes necessary, adds hugs amounts of time to the install.

I've commented out the time for now so this will not be a problem for anyone. When I readd it, I'll make an accommodation like the above for Void, etc.
