### ISSUE TITLE
Login fails on boot

### ISSUE THREAD

**Issue by drake-newell** [LukeSmithxyz/voidrice#414]
After running LARBS on Void, after login the system returns to the login prompt with the error:
`No keycodes found for keysym 65478.No keycodes found for keysym 65479. The server closed the connection. (III) Server terminated successfully (0). Closing log file.`
Does this have something to do with LARBS or is this a setup issue on my end?

**Comment by LukeSmithxyz** [comment]
I haven't testing LARBS on Void at all since the changes over the
weekend. I can go ahead and tell you that the problem is nearly
certainly not related to the keysym error though.

It's probably that there needs to be another program installed for the
graphical environment that is not installed as of now or that the
xinitrc isn't actually calling the WM correctly. That's the thing with
Void having so minimal of a package structure.

**Comment by drake-newell** [comment]
Hi Luke,
Hopefully you/someone else will be able to fix this issue. I would move over to Artix like you have, but for multiple reasons I have to remain on Void for now.

**Comment by drake-newell** [comment]
Since this same issue arose when I pulled from master in my original install of Void (before I tried out Artix for a short time) that had all the programs needed for DWM to boot pre-update, I'm going to guess the issue is in xinitrc.

**Comment by LukeSmithxyz** [comment]
Well, could you just comment out the stuff in `~/.xinitrc` and see if just having `exec dwm` or `exec i3` works?

**Comment by MuntashirAkon** [comment]
I've installed void linux few days ago. It had multiple issues with X11. You should post the whole log instead of just the last ones. For X11, the logs at the front seem to help more.
