### ISSUE TITLE
[Question] what is lmc and where to get it

### ISSUE THREAD

**Issue by ngortheone** [LukeSmithxyz/voidrice#459]
Hey @LukeSmithxyz 

Found references to `lmc` in your config files.

Did not find any relevant scripts or packages... only this.
```
[~]$ rua search lmc
Name       Version        Description

lmc        1.2.35-2       LAN Messenger is a p2p chat application for intranet communication and does not require a server. A variety of handy features are supported including notifications, personal and group messaging with encryption, file transfer and message logging.
```

**Comment by Daja177** [comment]
`lmc` is a script that was removed in 2e2200b4b96436fbfee59c74bfeb9f7e417a84df because it's redundant. Its purpose was to simplify mpd and pulsemixer's audio commands, but it was never really used outside of other scripts. Seems like Luke's forgotten to remove its references in the i3 config, I'll create a pull request to fix this.

Thanks for bringing this to our attention!
