### ISSUE TITLE
Vim - replace <++> is missing

### ISSUE THREAD

**Issue by Pwhitcomb** [LukeSmithxyz/voidrice#476]
Unable to preform replace using Space Tab or leader tab
Am I messing something up?

**Comment by Daja177** [comment]
@Pwhitcomb The guides and other features were removed in a89697cd752329aa5fe36c82655862cb09a984ac, but you can easily add those lines to your own vimrc. Check the commit and look for the line containing `" Navigating with guides` and below.

Or you could just copy those lines here:
```vim
inoremap <leader><leader> <Esc>/<++><Enter>"_c4l
vnoremap <leader><leader> <Esc>/<++><Enter>"_c4l
map <leader><leader> <Esc>/<++><Enter>"_c4l
```

The key combination is `leader` + `leader`, which in Luke's vimrc defaults to `,`.

**Comment by Pwhitcomb** [comment]
@Daja177 Thank you! Is there a specific reason these were removed or was it just by Luke's choice?

**Comment by Daja177** [comment]
@Pwhitcomb I don't have an exact answer as to why they were removed, but I guess it's because they're just very personalized macros that often went unused by most users. Luke has made a [video](https://www.youtube.com/watch?v=Q4I_Ft-VLAg) about this in the past if users want to create their own though.

Remember to close this issue afterwards unless you have any further concerns
