### ISSUE TITLE
`zsh` says weird things at launch

### ISSUE THREAD

**Issue by jcguu95** [LukeSmithxyz/voidrice#485]
Whenever `zsh` is turned on, two lines show up on the top before the prompt:

```
run-help=man
which-command=whence
[user@me ~]$
```

This is not the case for `sh` or `bash`. While it's not a big deal, it's a bit annoying. Any idea why this is the case? I have read through all `.*profiles*` but still have no clue..

**Comment by jcguu95** [comment]
Finally found the line that causes the problem by commenting out one by one.. I merged old LARBS and new LARBS setting manually, and did not remove a redundant file. Sorry for that.

**Comment by c-torre** [comment]
Necro bump because it happened to me and solution was not provided in the original issue.

The problem was in the sourced `.zshrc` file. Comment or remove the following line loading aliases:

```
[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/shortcutrc" ] && source "${XDG_CONFIG_HOME:-$HOME/.config}/shortcutrc"
```
The legacy `shortcutrc` file contained a single `alias` call which was executed when `.zshrc` was loaded by `zsh`. `shortcutrc` can therefore be removed after this change.
