### ISSUE TITLE
The LARBS Tutorial is outdated

### ISSUE THREAD

**Issue by shtangetki** [LukeSmithxyz/voidrice#489]
Specifically: the section - Status Bar mentions ~/.local/bin/dwmbar which no longer exists, the section - Key Bindings mentions ~/repos/ which no longer exists and is also mentioned in the Configuration section.

**Comment by vladdoster** [comment]
@shtangetki fix it then?

**Comment by LukeSmithxyz** [comment]
I haven't updated it in a while because I'm constantly changing my goals of where I want everything to be, that's all. I'll probably have it fixed in a bit.

**Comment by LukeSmithxyz** [comment]
I should say the additional reason is that there needs to be different instructions for dwm/i3.

**Comment by LukeSmithxyz** [comment]
I've basically fully updated the dwm tutorial and it is now built into my dwm build, installing the groff file and reading it in zathura on the key bind.

So that actually makes things easier for the general guide in this repo, because I was always unclear as to whether focus it on the i3 or dwm version, but now we can say it's all i3.

Anyway, I'll probably work on it some time this week, but if anyone wants to go ahead and PR changes, you're welcome.

**Comment by LukeSmithxyz** [comment]
I've now updated it all. Should be taken care off. If I missed any little thing, I'm sure it will be pointed out.
