### ISSUE TITLE
dwm crashes on Manjaro - How can I debug dwm?

### ISSUE THREAD

**Issue by IvoLeist** [LukeSmithxyz/voidrice#494]
Hi Luke,

I stumbled over your youtube channel while searching for videos explaining `zsh`
Clicking through your channell the suckless software hooked me immediately.
So I gave your LARBS voidrice a chance.

long story short
i3 works flawlessly 💯 
dwm unfortunately not

Loggin to my system in console mode and executing `startx`
shows the GUI for a second before it crashes with a lot of errors:

> /.local/bin/setbg: line 11: type: wal: not found
> sh: crypto command not found
> .local/bin/statusbar/volume: line 19 : [:46 integer expression expected
> cat: /sys/class/power_supply//capacity: No such file or directory
> **dwm: fatal error: request code=139 error code=16**
> etc

How can I debug dwm ?

Best regards,
Ivo

**Comment by vladdoster** [comment]
1. `pywal` needs to be installed. Whoever added the addition didnt check their logic. Check [here](https://github.com/LukeSmithxyz/voidrice/blob/master/.local/bin/setbg)

2. For the crypto package, not too sure. 

3. Status bar error due to bad shell programming. Try plugging the [script](https://github.com/LukeSmithxyz/voidrice/blob/2eb4f10b84c3918c178675a5d32cc457209a38f9/.local/bin/statusbar/volume#L19) into [shellcheck](https://shellcheck.com).

4. There is some code in [battery](https://github.com/LukeSmithxyz/voidrice/blob/2eb4f10b84c3918c178675a5d32cc457209a38f9/.local/bin/statusbar/battery#L15) which doesnt exist for some reason on your system. Again, bad shell programming. 

Id suggest fixing the issues with some if/else bash conditionals to check if the files exist and deal with it.

**Comment by LukeSmithxyz** [comment]
I'm still finalizing the current dwm bulid right now. The errors from the statusbar shouldn't be fatal though (most of them are supposed to happen because they are checking for batteries, etc.), there is probably some other issue going on.

If you run `pacman -Qm libxft-bgra`, does anything show up? If not, run `yay -S libxft-bgra`.

The volume error I suppose is related to Manjaro using pulseaudio by default. I should probably work in dealing with that automatically since there are so many people who use it.

**Comment by IvoLeist** [comment]
@vladdoster thank you for your suggestions especially for showing me shellcheck never used it but I guess it will come handy on day. (Btw. the link is wrong: https://www.shellcheck.net/)

@LukeSmithxyz thanks a lot for resolving that issue so quickly
`yay -S libxft-bgra` did the trick. Unfortunately I had to remove libxft so fingers-crossed that this did not break anything important.

**Comment by kronikpillow** [comment]
hi guys, libxft-bgra doesn't get installed when installin LARBS, possibly due to a conflict with libxft and yay doesn't allow the --noconfirm when there is a conflict so it just skips the package (or i dunno how to make it to allow to solve the conflict with --noconfirm) ... you need to install it and it should work after

**Comment by LukeSmithxyz** [comment]
I didn't realize that `--noconfirm` didn't work in this case. I suppose I could change it to `yes | yay -S --noconfirm`, but I'm trying to think of a circumstance where that might break...
