### ISSUE TITLE
Consider using sx instead of xinit and startx

### ISSUE THREAD

**Issue by astier** [LukeSmithxyz/voidrice#511]
[sx](https://github.com/Earnestly/sx) is a simple alternative to both xinit and startx for starting an Xorg server. Possible advantages:

- much smaller and simpler (check out the code)
- less dependencies
- the config-file must not be stored in the home-directory but in .config

I am using sx on arch for a year and had no issues. It can be installed via `pacman -S sx`

**Comment by LukeSmithxyz** [comment]
My first reflex would actually be to unceremoniously dismiss this possibility just because though those are all good advantages, I'm always suspicious of even simpler alternatives of system "basics". Although I suppose LARBS does explicitly install xinit, so I don't know if I could really call it a basic.

But I guess there is another huge advantage that this could give me: I've had a lot of trouble allowing LARBS to be drop-in compatible on people's machines who use DMs/login-screens (which I never and will never use). I suppose, however I might be able to use this to properly separate the required settings.

So I could clearly replace `~/.xinitrc` with this, but what about `~/.xprofile`?

**Comment by astier** [comment]
I don't know about xprofile. Never used it. I also never used login-screens so don't know how this would work out. Anyway, I just wanted to make you aware of sx. You can close this if you want.

**Comment by LukeSmithxyz** [comment]
Actually, here's what I might do.

- Use sx.
- Have it source `~/.config/xprofile` where the contents of `~/.xprofile` now are kept.
- For the time being, make a link in `~/.xprofile` to `~/.config/xprofile` to maintain compatibility with DMs.
- Note in the file that non-DM-users may delete the link.

**Comment by astier** [comment]
Just be aware of the differences which are listed in the sx-repo. Also there is an issue open which says that it will likely never work on BSD https://github.com/Earnestly/sx/issues/7
