### ISSUE TITLE
How to switch to the second monitor in dwm without a mouse operation

### ISSUE THREAD

**Issue by shiruigithub** [LukeSmithxyz/voidrice#541]
Hi luke, I want to know how to switch to the second monitor in dwm without the mouse. I have tried "Mod + <" and "Mod + >" but it doesn't work for me. This is my first time to use dwm on linux, please help me. Thanks

**Comment by drake-newell** [comment]
FYI this should be in the dwm repo, buy you need to add a keybinding for "focusmon" (just follow the format from the other keybinds). Same for "tagmon" if you want to send a tag to the other monitor. I would suggest binding it to left (XK_Left) and right (XK_Right) arrow to move left and right through the monitors since Luke doesn't use it for anything. Mine looks like this If you just want to copy it into your config.h. Make sure to make && sudo make install to recompile dwm after.
`{ MODKEY, XK_Left, focusmon, {.i = -1 } },	{ MODKEY, XK_Right, focusmon, {.i = +1 } },	{ MODKEY|ShiftMask, XK_Left, tagmon, {.i = -1 } },	{ MODKEY|ShiftMask, XK_Right, tagmon, {.i = +1 } },`

**Comment by shiruigithub** [comment]
Thanks drake-newell. You solved the problem.

**Comment by drake-newell** [comment]
Feel free to close this issue.
