### ISSUE TITLE
Change Terminal Colors Immediate 

### ISSUE THREAD

**Issue by smhmd** [LukeSmithxyz/voidrice#560]
In a recent video, you say that terminal colors don't change immediately, @LukeSmithxyz. Here's a possible solution:  https://github.com/sos4nt/dynamic-colors

**Comment by mokulus** [comment]
Can you check it again? After I use `wal -i ...` st changes colors immediately.

**Comment by smhmd** [comment]
@mokulus if it does, I'll close the issue. I don't use luke's st build. This was a mere suggestion.

**Comment by AlexSyssoyev** [comment]
As far as i know the video showed how to change the terminal colors editing the Xresources file, not using pywal. It makes sense that you have to reload the terminal in order to get the color scheme changed.

Personally i don't use Xresources and i think it wouldn't be worth it to try to implement this just for saving two seconds.

**Comment by smhmd** [comment]
@AlexSyssoyev It's not about saving two seconds but rather saving state. I don't really care, though.
