### ISSUE TITLE
Dropdown terminal + math not working (atleast on my side)

### ISSUE THREAD

**Issue by ExploXd** [LukeSmithxyz/voidrice#57]
Well, I can't figure out what is causing this issue.

I have st and tmux but it doesn't work for me. Be free to ask me for some log files.

**Comment by LukeSmithxyz** [comment]
Did you install my dotfiles manually or via LARBS?

Do you have the `~/.scripts/` directory in your $PATH variable?

Try running `tmuxinit` manually in a terminal.

**Comment by ExploXd** [comment]
well, I installed larbs on fresh arch installation.

yes, I do have ~/.scripts in my $path variable.

tmuxinit output:
`-bash: clear: příkaz nenalezen (command was not found) // I think that's an issue in my i3 config`
but tmuxinit works.

but still, pressing $mod+u won't do anything at all.

**Comment by LukeSmithxyz** [comment]
The command `clear` isn't found on your instance of bash? Something weird is going on... Are you using some unique version of bash or something?

I'm not exactly sure what's causing this not to work, but I'll explain the specifics if you can intuit what the problem is for you. When i3 starts the first time, it spawns a terminal labelled `dropdown` which will run the `tmuxinit` command (due to i3's wonkiness, this has to be a separate script).

All `tmuxinit` does is attempt to connect to an existing tmux session, and if impossible, starts a new tmux session. Note that this window is only spawned with you **first** start i3, not when you refresh or press `mod+u`, so if you want to troubleshoot it, be sure to exit i3 and restart to do so. Note that all of this is true of the `math` window too, with the `dropdowncalc` script, it attempts to start `R` if you have it, otherwise `python`.

What seems to be happening is that neither of these scripts run properly, and thus the windows spawn and immediately die. This is why I ask if you're using a different version of bash. Hypothetically, I could imagine language interfering with this as well. You might want to try switching to English, rebooting and seeing what happens, but that's just me grasping at straws.

**Comment by ExploXd** [comment]
Oh god. I'm using normal Bash included with Arch Linux.
Clear itself works in the terminal so I don't know. I will try zsh.

**Comment by ExploXd** [comment]
This doesn't work. But I reinstalled Arch because I have got a new drive. And I can confirm that dropdown doesn't work on clean Arch install with Larbs. Firstly tmuxinit wasn't set as an alias so I did. And it doesn't work. Now I believe that it's an issue with your config. Tmux itself works. Tmuxinit works too. Pressing $mod + u or a just doesn't work.
