### ISSUE TITLE
Brave wont install extensions

### ISSUE THREAD

**Issue by kronikpillow** [LukeSmithxyz/voidrice#571]
Now i know this probably isnt a larbs issue, but after reporting the issue to upstream, and to the package maintainer, im starting to suspect it is ... for a while now, I'm unable to install Chrome webstore extensions on Brave, when I go to the store and click add to Brave, the download interupts ... I'v tried downloading the extension with a extension downloader service, and once it downloads and i drag and drop the extension to brave, all it does is re-prompt me to download it, and redownloads it, it doesn't install

issue reported to upstream : [upstream](https://github.com/brave/brave-browser/issues/9138)
issue reported to pkg maintainer [pkg maintainer](https://aur.archlinux.org/packages/brave-bin/#news)
[video of issue](https://youtu.be/M2RGbAlOyt8)
both claim that on their side things work fine ... is anyone else on LARBS experiencing this problem?

**Comment by kronikpillow** [comment]
I should probably note that im on a freshly installed larbs system from 5 mins ago :D

**Comment by LukeSmithxyz** [comment]
Oh you know what, it is a LARBS issue.

They say that Brave does autoupdates, I've never seen this on Linux, but I preemptively blocked the update site in `/etc/hosts`, which apparently is also used by the Chrome store. I think I'll unblock that particular url, because while I obviously don't use the Chrome store, I'm sure it could a big and mysterious inconvenience for others.

**Comment by kronikpillow** [comment]
xDD
