### ISSUE TITLE
statusbar huh?

### ISSUE THREAD

**Issue by kronikpillow** [LukeSmithxyz/voidrice#573]
[em????](https://0x0.st/iQWG.png)

**Comment by LukeSmithxyz** [comment]
Oh, apparently there's a bash built in `help`? I guess I'll just rename the help module, although this never happened before on i3. Might be with how directories are added to `$PATH`.

This doesn't happen on my system since I have dash as `sh`.

I might want to rename some other statusbar modules since some of them have pretty generic names...
