### ISSUE TITLE
How did you create the emoji file?

### ISSUE THREAD

**Issue by kaihendry** [LukeSmithxyz/voidrice#608]
Hi fellow Youtuber Luke, I'm curious how you generate:
https://github.com/LukeSmithxyz/voidrice/blob/master/.local/share/larbs/emoji

https://s.natalian.org/2020-04-30/emoji-dmenu.mp4

I'm using Arch packaged dmenu 4.9-1 and it's quite often slow. Is it slow for you too Luke?

I'm also using libxft-bgra btw.

**Comment by LukeSmithxyz** [comment]
The slowness, I'm pretty sure, is a result of font symbols not being found. The same has happens to me when I use a font without full unicode coverage. I have Joypixels installed and I have it as one of dmenu's backup fonts for this reason. If I uninstall joypixels and some other emoji-providing font packages, I get the same lag again. I'm using Liberation mono as my default monospace font now and it has pretty good unicode coverage; I don't know about Terminus.

I also just have all my suckless tools look to my fontconfig monospace font, rather than having my font set individually in each program. This might make a difference too.

If you want to know how I generated the file, I think I had just gone to the Wikipedia page listing all the current emojis and did some awking or something to get it in the format I wanted.

**Comment by nycex** [comment]
About the generating: With the new unicode characters in 2020 I wanted to update the file so I made a script that generates it, though it doesn't download fontawesome characters, so if you need a script that downloads them, [here is mine](https://codeberg.org/nycex/dotfiles/raw/branch/master/dev/sh/download-emoji-list).

**Comment by vladdoster** [comment]
> Hi fellow Youtuber Luke, I'm curious how you generate:
> https://github.com/LukeSmithxyz/voidrice/blob/master/.local/share/larbs/emoji
> 
> https://s.natalian.org/2020-04-30/emoji-dmenu.mp4
> 
> I'm using Arch packaged dmenu 4.9-1 and it's quite often slow. Is it slow for you too Luke?
> 
> I'm also using libxft-bgra btw.

Cool seeing you on here, love your content. Super refreshing that it's usually single take footage.
