### ISSUE TITLE
Polybar [module/temperature] bugged?

### ISSUE THREAD

**Issue by CecileGS** [LukeSmithxyz/voidrice#61]
Currently the temp reading never changes and only ever displays 28°C (at least on my end). I fixed it myself with the help of the `sensors` package to make it show my CPU temps in real-time instead.

I made a lot of changes to my polybar config, actually. I'm not sure how many changes I should submit in a PR though, but just submitting my fix for this one module is fine right? The problem with my fix is that it introduces another dependency for LARBS which I'd like to avoid if possible.

**Comment by LukeSmithxyz** [comment]
Polybar isn't really "officially supported" by my dotfiles, as I don't use it anymore. It wouldn't make sense to add anything polybar-related to LARBS because polybar isn't even installed itself.

That said, I never had your original problem when using Polybar (my CPU temperature always updated), but it might be a machine-specific problem. If you want to submit minor bug fixes for Polybar, that's fine.

**Comment by LightGSD** [comment]
Ah okay gotcha. The fact that the

**Comment by LightGSD** [comment]
Ah okay gotcha. The fact that the p

**Comment by CecileGS** [comment]
[what the fuck, phone posting on third party apps is hella retarded... -_- sorry about spamming earlier]

**Comment by CecileGS** [comment]
I was thrown off by the line of code vaguely mentioning support for Polybar and the accompanying config files, and yeah I know that the user needs to install Polybar from source via Git or the AUR.

It's hard to know what the overarching direction of LARBS as a whole and what features are high priority without a contributors guide. All the code and references pertaining to Polybar can be deleted to make the main repo cleaner, and I suppose a separate branch/fork for a Polybar variant could be maintained - like how there's i3 and i3-gaps.
