### ISSUE TITLE
`libxft-bgra` Out-of-date, and unable to import gpg keys.

### ISSUE THREAD

**Issue by lukerb52** [LukeSmithxyz/voidrice#769]
I think the two problems are related. when running `yay -S libxft-bgra` It runs smoothly until the import GPG key step, to which it gives this error:

```
gpg: keyserver receive failed: General error
problem importing keys
``` 
`X` crashes after about a second without `libxft-bgra`.

**Comment by narukeh** [comment]
# **This is not a larbs issue**
@lukerb52  just:
`gpg --keyserver keys.gnupg.net --recv-keys 4A193C06D35E7C670FA4EF0BA2FB9E081F2D130E`
if it gives an error, you have to `mkdir ~/.local/share/gnupg`
In the future just read the aur page of wanted package instead of making a new issue here 😉✌️ (dont forget to close this issue)
Tip: after you import the keys, and install the package, save and upload it somewhere and then you can just
`sudo pacman -U 'https://DOMAIN.COM/libxft-bgra-2.3.3.r7.7808631e-1-x86_64.pkg.tar.xz'`

**Comment by vladdoster** [comment]
@narukeh you're right it isn't a larbs issue nor is it a voidrice issue!

**Comment by lukerb52** [comment]
Thanks!
