### ISSUE TITLE
New alias pz doesnt work.

### ISSUE THREAD

**Issue by void00r** [LukeSmithxyz/voidrice#804]
I saw luke added new alias 
`pz="pacman -Qi | awk '/^Name/{name=$3} /^Installed Size/{print $4$5, name}' | sort -h"`
 Which apparently doesnt work on my Artix build. Need guidance what dependacies or extra stuff needed to make it work.

**Comment by vladdoster** [comment]
1. Artix does not use Pacman. 

2. It probably doesn't get the same output because of the first reason I list.

It is for you to figure out how to convert it to work with Artix pkg manager and awk the appropriate values.

**Comment by void00r** [comment]
Are you kidding me. Artix is Arch. It DOES use pacman. I use Artix myself. And So luke.

**Comment by vladdoster** [comment]
> Are you kidding me. Artix is Arch. It DOES use pacman. I use Artix myself. And So luke.

Got mixed up with another issue about PKG managers, so chill.

Break it down pipe by pipe and see where the command is breaking.

**Comment by void00r** [comment]
I see. btw that alias is no longer on aliasrc now.

**Comment by void00r** [comment]
I got to say you have some serious needed
Messed up psychological issues with non soystemd distros.Thats why you constantly throwing thumbs down on my comment.

**Comment by vladdoster** [comment]
> I got to say you have some serious needed
> Messed up psychological issues with non soystemd distros.Thats why you constantly throwing thumbs down on my comment.

I don't have any problem with what init system anyone uses. I don't run a systemd system. I use MacOS which uses `launchctl`. 

I added the thumbs down because of how you're talking to someone trying to help you. The initial issue isn't too hard of an issue to get to the root cause of if you just Isolate where it is breaking in the pipes. 

My advice? Learn how to google around and see if you can figure it out on your own. It helps in the long run.

Here is the first google result when searching `debugging pipe commands`

http://www.softpanorama.org/Scripting/Piporama/debugging.shtml

```
That means you debug each pipe stage on different datasets separately as a single program using as input file written by previous stage for specific dataset until output of this stage fully satisfies you. After that you move to the next stage. And so on until the whole pipe is debugged. 

You can use tee on any stage of the pipe to divert output to a file.

An additional useful component that simplifies pipe debugging is pv (Pipe Viewer).
```

**Comment by Aeres-u99** [comment]
```
0.00B base
0.00B ca-certificates
0.00B pulseaudio-alsa
64.00B update-grub
694.00B fuse-common
809.00B dnssec-anchors
1974.00B pambase
2.38KiB termite-terminfo
3.40KiB xorg-fonts-alias-75dpi
3.49KiB xorg-fonts-alias-100dpi
4.35KiB rxvt-unicode-terminfo
4.64KiB systemd-sysvcompat
6.04KiB ca-certificates-utils
6.13KiB powerline-common
6.42KiB i3-gnome-pomodoro-git
7.70KiB kunst-git
11.82KiB python-termcolor
12.49KiB perl-file-listing

...

276.71MiB marktext-bin
488.56MiB go
502.28MiB wine
558.60MiB linux-firmware

 .--.                  Pacman v5.2.2 - libalpm v12.0.2
/ _.-' .-.  .-.  .-.   Copyright (C) 2006-2020 Pacman Development Team
\  '-. '-'  '-'  '-'   Copyright (C) 2002-2006 Judd Vinet
 '--'
                       This program may be freely redistributed under
                       the terms of the GNU General Public License.

```
I am on Arch and it seems to work, can you please confirm the version @void00r ?

**Comment by void00r** [comment]
> > I got to say you have some serious needed
> > Messed up psychological issues with non soystemd distros.Thats why you constantly throwing thumbs down on my comment.
> 
> I don't have any problem with what init system anyone uses. I don't run a systemd system. I use MacOS which uses `launchctl`.
> 
> I added the thumbs down because of how you're talking to someone trying to help you. The initial issue isn't too hard of an issue to get to the root cause of if you just Isolate where it is breaking in the pipes.
> 
> My advice? Learn how to google around and see if you can figure it out on your own. It helps in the long run.
> 
> Here is the first google result when searching `debugging pipe commands`
> 
> http://www.softpanorama.org/Scripting/Piporama/debugging.shtml
> 
> ```
> That means you debug each pipe stage on different datasets separately as a single program using as input file written by previous stage for specific dataset until output of this stage fully satisfies you. After that you move to the next stage. And so on until the whole pipe is debugged. 
> 
> You can use tee on any stage of the pipe to divert output to a file.
> 
> An additional useful component that simplifies pipe debugging is pv (Pipe Viewer).
> ```

I dont have problem with you thumbs downing on my Issue question. I was talking about thumbs down on that "Are you kidding me?" comment? Dont try to justify your actions you already caught red handed.

**Comment by vladdoster** [comment]
I don't think it's being caught red handed if I didn't hide it? 


Your reaction was an overreaction from a mistake in where I mixed up void and Artix due to your name because the issue I linked is about void and pkg managers.

**Comment by LukeSmithxyz** [comment]
This alias in question was never added to my dotfiles. I closed the PR here: https://github.com/LukeSmithxyz/voidrice/pull/799

I'm pretty strict as to what I add as an alias, and this was a little niche.

Aside from that, it was broken: The reason this alias does not function is because it confused arguments to bash with awk elements. That is, if coined as an alias as is, `$3`, `$4` and `$5` will be looking for arguments to __bash/shell__, which normally there are none, so each will be empty.

To fix this, either add a `\` before each `$` or coin a function `pz` with the original content and it will work.

**Comment by void00r** [comment]
Thanks Luke I will try to make it work. And Sorry for nonsense mess happened here.
