### ISSUE TITLE
Can't use eyeD3 or youtube-dl shortcuts in ranger

### ISSUE THREAD

**Issue by Unser395** [LukeSmithxyz/voidrice#813]
Hello,

I'm trying to use the "ytv" and "yta" shortcut inside ranger, and to copy paste a link inside the file manager, but it's never downloading anything. Youtube-dl is properly installed.

Same with the audio tagging shortcuts. eyeD3 is installed but no shortcuts seem to rename the tracks in any way.

What can I do in order fix that ? 
Thank you very much for all the work and have a nice day

**Comment by LukeSmithxyz** [comment]
I don't maintain the ranger config anymore so it might be some change in ranger.

I don't have eyeD3, but I downloaded ranger and tried the youtube-dl commands and the issue is that since zsh is the default shell now, you have to either quote the url or escape the question mark. Might also be something shell related for eyeD3.
