### ISSUE TITLE
dmenu doesn't change colour

### ISSUE THREAD

**Issue by qwedas** [LukeSmithxyz/voidrice#84]
when I'm in ranger and press "bw" It doesn't change dmenu's colour.

**Comment by LukeSmithxyz** [comment]
Yes. dmenu doesn't read Xresources colors, including those from pywal.

There are extremely hackly and inelegant ways of bypassing this, for example you can see [here](https://github.com/dylanaraps/pywal/wiki/Customization#dmenu) in the pywal manual. This would mean adding a bunch of crap to every place dmenu is called, which I don't want to do especially because when there's a real solution I'll have to delete all of it.

I/you might want to open a issue/request on my own [dmenu repo](https://github.com/LukeSmithxyz/dmenu) on this, but it's not really a LARBS/voidrice issue. I don't know that much about C to instantly do the patch myself, but if it can be done for st, it can be done for dmenu.
