### ISSUE TITLE
i3resize not working

### ISSUE THREAD

**Issue by darkralts** [LukeSmithxyz/voidrice#840]
bindsym $mod+Shift+y		exec --no-startup-id i3resize left
bindsym $mod+Shift+u		exec --no-startup-id i3resize down
bindsym $mod+Shift+i		exec --no-startup-id i3resize up
bindsym $mod+Shift+o		exec --no-startup-id i3resize right

i put that in my config but it doesnt work

**Comment by darkralts** [comment]
am i missing a dependancy?

**Comment by vladdoster** [comment]
i3 isn't supported anymore.

**Comment by vladdoster** [comment]
Id assume one of these will hold your answer.

[Related issues](https://github.com/LukeSmithxyz/voidrice/issues?q=is%3Aissue+resize+is%3Aclosed)

this [issue](https://github.com/LukeSmithxyz/voidrice/issues/147) looks promising.

Would you mind closing this issue because
1. Since i3 isn't supported anymore in this repo
1. This is not a LARBS issue. There are better resources to ask questions like this. Try the i3 subreddit.
1. rtfm. These bindings behavior are in the documentation.

**Comment by vladdoster** [comment]
And that colors issue you're facing .... It's a config option in kitty. Kitty's config is very well documented. 

Please just rtfm.

**Comment by darkralts** [comment]
sure thing, i just posted it here because well this is the source of it, i
copied it from luke smiths config, thanks for the possible solutions i will
check them out
