### ISSUE TITLE
Weird Caps Lock wrong expected behaviour

### ISSUE THREAD

**Issue by pavilion** [LukeSmithxyz/voidrice#88]
Caps Lock works as a Mod key, and I do not want that.
While I'm pressing it, it works as a Mod key and when I stop pressing it is when it actually works as an escape key. 
I would like to know how can I make Caps Lock works just as Escape, and keep the Mod functionality for the Windows Key.
I've tried `setxkbmap -layout gb  -option caps:escape` but still having the same problem. Went to my .i3/config file but don't know what to actually change in order to get the behaviour I want

**Comment by LukeSmithxyz** [comment]
Caps is dually mapped to be usable as escape if pressed and super if held down. This is expected behavior. As the manual states, any bindings can be changed by changing `~/.scripts/remaps`.

If you want escape to function only as escape, comment out the `xcape` command and replace the `setxkbmap` command with the one you listed in your post.

**Comment by pavilion** [comment]
Hi! I would like to reopen this since ~/.scripts/remaps is empty in newer voidrice's, may I ask where should I change that option now? Thanks

**Comment by PrangerStefan** [comment]
As of c6e69e96421ebf192eb6de537324e269e7bfda78 this file has been moved to `~/.local/bin/remaps`, for anyone looking for that file.
