### ISSUE TITLE
Emoji and Status Bar Issues

### ISSUE THREAD

**Issue by LukeSmithxyz** [LukeSmithxyz/voidrice#92]
LARBS will install `ttf-emojione` as the default emoji font. For people non-minimal installs (like Arcolinux), this will interact in strange ways with previously installed fonts, causing emojis on the status bar to become enormously large.

## Ideal fix

- Specify the emoji font in `fonts.conf`. I'm not familiar with fontconfig syntax, to be honest. I've tried some things found in internet searches but without success. Emojis seem to work a little different from other characters, so anyone who knows more about that, please feel free to give a solution. This is probably something really simple.

## Temporary fixes

- Users can replace `ttf-emojione` with `ttf-emojione-color`. This works, but ironically replaces the colored emoji with non-colored ones.
- This also may be band-aided by fonts installed in a different order. I just shifted the LARBS install order so that `ttf-emojione` is installed last of all the fonts instead of the first. This can make a difference in what is determined as the default font, but I haven't tested it yet.

**Comment by ExploXd** [comment]
what if you first make pacman uninstalling that, and then installing that? this will rebuild the font cache, and this also may fix your issue.

**Comment by LukeSmithxyz** [comment]
Lol that would be an extremely skiddy thing to do when the intended solution would just be a change in the config or me running a refresh of the font cache. The latter can easily be added to LARBS, but I'm not sure if it will work as an ad hoc solution anyway. I want to force the intended fonts with fontconfig, which would be the real solution.

**Comment by LukeSmithxyz** [comment]
Lol. Here's how you do the "impossible" task of editing fonts.conf:

```
vim ~/.config/fontconfig/fonts.conf
```

**Comment by deadsidestar** [comment]
Luke, Just to let you know, I'm one of the developers of ArcoLinux & I personally use your i3 config.
In our next release which will be on September 15th I have fixed this issue. What the problem was is in the /etc/fonts/conf.avail/ there was a file missing "10-scale-bitmap-fonts.conf". I have added it & created the symlink to it in  /etc/fonts/conf.d it works as expected.
We also have a minimal build called ArcoLinuxD (fixed as well for the release on the 15th) which is bascially just Arch with few extra packages installed (no desktop) which works great with Larbs (which I'm using at the moment).
