### ISSUE TITLE
[idea] make some command to update LARBS

### ISSUE THREAD

**Issue by ExploXd** [LukeSmithxyz/voidrice#93]
hello, so I would like if I was able to just write `lu`(lARBS uPDATE) in the terminal and process will start (no auto-updates so it doesn't behave like micro$hit)

**Comment by hepan-git** [comment]
Yeah, I was just wondering how to update LARBS. Because if I were to download one of the files to overwrite mine it would get rid of all my customizations.

**Comment by LukeSmithxyz** [comment]
Well you can easily run:
```
git fetch --all
git reset --hard origin/master
```
To update your repo. This, however will overwrite config changes you've made. I'm trying to figure out what the best git solution is for manually picking what to overwrite.

**Comment by hepan-git** [comment]
For now, I will manually copy paste an update in if I really want it or need it.

**Comment by SaltyClaridge** [comment]
Updating is a tricky thing because so many people have different preferences for how to handle it. Personally, I don't mind going through the changes on here and manually copying them over as needed. I also don't mind reinstalling the entire system because I'm not one to customize a whole lot. I can usually reinstall and be back where I was in 45 minutes.

**Comment by hepan-git** [comment]
I can't get back to where I was very quickly because it takes me a while to download things since my internet isn't very good. I am also semi-new to Linux (I used Mac for a few years, which I could use vim, ranger, and I found a tiling wm as well) so I would have to google a lot of the tutorials again.

**Comment by SaltyClaridge** [comment]
Not much you can do about slow internet, but if you haven't already, I would suggest [updating your mirror list](https://www.archlinux.org/mirrorlist/). I also keep a small file that has every step of all the little changes I made just in case I want/need to start over with a clean system.

**Comment by hepan-git** [comment]
I could also upload the dotfiles to my own github, it would take a while at first but afterwards it is just small <1mb updates.

**Comment by gabriel-doriath-dohler** [comment]
https://www.gnu.org/software/stow/ could be useful. Dotfiles should be stored in ~/.dotfiles-user and symlinked to ~.
When updating, download voidrice to ~/.dotfiles-voidrice, track both folder with git separately. Then sync both repo (~/.dotfiles-user and ~/.dotfiles-voidrice). It work the same way as synced forks.

**Comment by gabriel-doriath-dohler** [comment]
I guess `git merge-tool` could be used to resolve conflicts.

**Comment by LukeSmithxyz** [comment]
I'm going to be adding some documentation on updating this with git in the next big update. Possibly with an associated video. Closing this issue for cleanliness's sake.
